In [3]:
import numpy as np

**Dominant Value Function**

In [14]:
def dominant_value(matrix):
    eigenvalues = np.linalg.eigvals(matrix)
    return max(eigenvalues, key=abs) #max to use the absolute value of each eigenvalue
matrix = np.array([[4, 2], [3, 1]])
print("Dominant Eigenvalue:", dominant_value(matrix))

Dominant Eigenvalue: 5.372281323269014


**Inverse Matrix Function**

In [19]:
def inverse_matrix(matrix):
    dominant_eigenvalue = dominant_value(matrix)
    if dominant_eigenvalue == 0:
        raise ValueError("Matrix is singular and cannot be inverted.")
    inverse = np.linalg.inv(matrix)
    return inverse
matrix = np.array([[4, 2], [3, 1]])
print("Inverse Matrix:\n", inverse_matrix(matrix))

Inverse Matrix:
 [[-0.5  1. ]
 [ 1.5 -2. ]]


**inverse of 3*3 matrix**

In [34]:
import numpy as np
A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
#inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


**Identity Matrix Function**

In [31]:
def identity_matrix(matrix):
    size = matrix.shape[0] #matrix.shape would return (2, 2)
    identity = np.eye(size) #eye function creates an identity matrix.
    return identity
matrix = np.array([[4, 2], [3, 1]])
print("Identity Matrix:\n", identity_matrix(matrix))

Identity Matrix:
 [[1. 0.]
 [0. 1.]]
